//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.296
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PBTech.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "10.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("CREATE TABLE READING (r_id INTEGER PRIMARY KEY, r_date TEXT, r_name TEXT, r_descr" +
            "iption TEXT);")]
        public string CREATE_READING {
            get {
                return ((string)(this["CREATE_READING"]));
            }
            set {
                this["CREATE_READING"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("CREATE TABLE CHANNEL (c_id INTEGER PRIMARY KEY, c_rid INTEGER, c_details TEXT, c_" +
            "channelnumber INTEGER);")]
        public string CREATE_CHANNEL {
            get {
                return ((string)(this["CREATE_CHANNEL"]));
            }
            set {
                this["CREATE_CHANNEL"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("CREATE TABLE READING_DETAIL (rd_id INTEGER PRIMARY KEY, rd_rid INTEGER, rd_cid IN" +
            "TEGER, rd_time INTEGER, rd_point INTEGER );")]
        public string CREATE_READING_DETAIL {
            get {
                return ((string)(this["CREATE_READING_DETAIL"]));
            }
            set {
                this["CREATE_READING_DETAIL"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("INSERT INTO READING (r_date,r_name,r_description) VALUES (@date, @name, @descript" +
            "ion);\r\nselect last_insert_rowid()")]
        public string INSERT_READING {
            get {
                return ((string)(this["INSERT_READING"]));
            }
            set {
                this["INSERT_READING"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("INSERT INTO CHANNEL (c_rid,c_details,c_channelnumber) VALUES (@rid, @details,@num" +
            "ber);\r\nselect last_insert_rowid()")]
        public string INSERT_CHANNEL {
            get {
                return ((string)(this["INSERT_CHANNEL"]));
            }
            set {
                this["INSERT_CHANNEL"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("INSERT INTO READING_DETAIL (rd_rid,rd_cid,rd_time,rd_point) VALUES (@rid, @cid, @" +
            "time,@point);\r\nselect last_insert_rowid()")]
        public string INSERT_READING_DETAIL {
            get {
                return ((string)(this["INSERT_READING_DETAIL"]));
            }
            set {
                this["INSERT_READING_DETAIL"] = value;
            }
        }
    }
}
